image: node:18.18-bullseye-slim

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'staging'
 
default:
  cache:  # Cache modules in between jobs for the same branch if package-lock.json file changes
    key: 
      prefix: $CI_COMMIT_REF_NAME
      files:
        - server/package-lock.json
        - client/package-lock.json
    paths:
      - server/.npm/
      - client/.npm
  # run this before every job; will hit the cache first
  before_script:
   - cd server && npm ci --cache .npm --prefer-offline && cd ../client && npm ci --cache .npm --prefer-offline && cd ..

stages:
  - lint
  - build
  - test
  - release

lint-server:
  stage: lint 
  script:
    - cd server && ./node_modules/eslint/bin/eslint.js --ext js,mjs,cjs . 
  allow_failure: false

lint-client:
  stage: lint 
  script:
    - cd client && ./node_modules/eslint/bin/eslint.js --ext js,jsx,mjs,cjs .
  allow_failure: false

build-frontend:
  stage: build
  script:
    - cd client && npm i
    - npm run build
  only:
    refs:
      - main
      - master
      - staging
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - client/build

test:
  stage: test
  script:
    - apt-get update
    - apt-get install -y libcurl4
    - cd server 
    - npm i && npm test
  only:
    refs:
      - main
      - master
      - staging

build-app-archive:
  stage: release
  variables:
    RELEASE_FILE: release-$CI_PROJECT_NAME-$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA.tar.gz
  dependencies:
    - build-frontend
  # rules:
  # - if: $CI_COMMIT_TAG =~ /^v2\.[0-9]*\.[0-9]*$/
  before_script:
    - cd client && npm ci --omit dev
    - cd ../server && npm ci --omit dev
    - cd ../
  script:
    - tar -czvf $RELEASE_FILE client/build/ server/node_modules
  artifacts:
    expire_in: 7 days
    when: on_success
    paths:
      - ./$RELEASE_FILE
  only:
    refs:
      - main
      - master
      - staging